#!/bin/sh
# LambdaNative - a cross-platform Scheme framework
# Copyright (c) 2009-2020, University of British Columbia
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or
# without modification, are permitted provided that the
# following conditions are met:
#
# * Redistributions of source code must retain the above
# copyright notice, this list of conditions and the following
# disclaimer.
#
# * Redistributions in binary form must reproduce the above
# copyright notice, this list of conditions and the following
# disclaimer in the documentation and/or other materials
# provided with the distribution.
#
# * Neither the name of the University of British Columbia nor
# the names of its contributors may be used to endorse or
# promote products derived from this software without specific
# prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
# CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
# NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

SYS_IOSSDK=`xcrun -find -sdk $IOS_PLATFORM_TYPE --show-sdk-path`
SYS_IOSVERSION=$IOSVERSION
SYS_CC=`xcrun -find -sdk $IOS_PLATFORM_TYPE clang`" -arch $SYS_CPU"
assertfile $SYS_CC
# -DIOS is needed to build gambit
SYS_CC="$SYS_CC $SYS_DEBUGFLAG -isysroot $SYS_IOSSDK -DIOS -miphoneos-version-min=$SYS_IOSVERSION"
SYS_CC="$SYS_CC -fPIC -fsigned-char -fomit-frame-pointer $cflag_additions"
SYS_CXX=`echo $SYS_CC | sed 's/clang/clang++/'`
SYS_AR=`xcrun -find -sdk $IOS_PLATFORM_TYPE ar`
SYS_RANLIB=`xcrun -find -sdk $IOS_PLATFORM_TYPE ranlib`
SYS_STRIP=`xcrun -find -sdk $IOS_PLATFORM_TYPE strip`
assertfile $SYS_AR
assertfile $SYS_RANLIB
assertfile $SYS_STRIP
SYS_LD=`xcrun -find -sdk $IOS_PLATFORM_TYPE ld`" -arch $SYS_CPU"
SYS_WINDRES=
SYS_EXEFIX=
SYS_APPFIX=".app"

#eof
