#!/bin/sh
# LambdaNative - a cross-platform Scheme framework
# Copyright (c) 2009-2013, University of British Columbia
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or
# without modification, are permitted provided that the
# following conditions are met:
#
# * Redistributions of source code must retain the above
# copyright notice, this list of conditions and the following
# disclaimer.
#
# * Redistributions in binary form must reproduce the above
# copyright notice, this list of conditions and the following
# disclaimer in the documentation and/or other materials
# provided with the distribution.
#
# * Neither the name of the University of British Columbia nor
# the names of its contributors may be used to endorse or
# promote products derived from this software without specific
# prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
# CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
# NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# lipo the payload

payloads=`ls -1 $SYS_PREFIXROOT/ios/*/lib/libpayload.a | tr '\n' ' '`
ios_fatlib=$SYS_PREFIXROOT/ios/libpayload-fat.a
rmifexists $ios_fatlib
lipo $payloads -output $ios_fatlib -create
assertfile $ios_fatlib "lipo failed to create fat payload"

# overwrite the current arch payload with the fat one
mv $ios_fatlib $SYS_PREFIX/lib/libpayload.a

ios_subst()
{
  ac_subst IOS_OBJC_ADDITIONS "@$1/IOS_objc_additions"
  ac_subst IOS_OBJCPP_ADDITIONS "@$1/IOS_objcpp_additions"
  ac_subst IOS_OBJC_DEFINES "@$1/IOS_objc_defines"
  ac_subst IOS_FRAMEWORK_ADDITIONS "@$1/IOS_framework_additions"
  ac_subst IOS_FRAMEWORK_SEARCHPATH "@$1/IOS_framework_searchpath"
  ac_subst IOS_LAUNCHERAPPDELEGATE_ADDITIONS "@$1/IOS_launcherappdelegate_additions"
  ac_subst IOS_LAUNCHERAPPDELEGATE_DIDFINISHLAUNCHING "@$1/IOS_launcherappdelegate_didfinishlaunching"
  ac_subst IOS_XML_PERMISSIONS "@$1/IOS_xml_permissions"
  ac_subst IOS_XML_REQUIREDDEVICECAP "@$1/IOS_xml_requireddevicecap"
}
ios_subst loaders/ios
for m in $modules; do
  modpath=`locatedir modules/$m silent`
  ios_subst $modpath
done
ios_subst `locatedir apps/$SYS_APPNAME`

tgtdir="$SYS_PREFIX/$SYS_APPNAME$SYS_APPFIX"
srcdir=`pwd`"/loaders/ios"
cmakedir=`mktemp -d $SYS_TMPDIR/tmp.XXXXXX`
ac_output $srcdir/CMakeLists.txt $cmakedir/CMakeLists.txt
ac_output $srcdir/objc_additions.m $cmakedir/objc_additions.m
ac_output $srcdir/objcpp_additions.mm $cmakedir/objcpp_additions.mm
ac_output $srcdir/mo_chooks.mm $cmakedir/mo_chooks.mm
ac_output $srcdir/launcherAppDelegate.m $cmakedir/launcherAppDelegate.m
cp $srcdir/*.m $cmakedir
cp $srcdir/*.mm $cmakedir
cp $srcdir/*.h $cmakedir

echo " => preparing icons.."
cp "$SYS_PREFIXROOT/build/$SYS_APPNAME/artwork-57.png" "$cmakedir/Icon.png"
cp "$SYS_PREFIXROOT/build/$SYS_APPNAME/artwork-114.png" "$cmakedir/Icon@2x.png"
cp "$SYS_PREFIXROOT/build/$SYS_APPNAME/artwork-72.png" "$cmakedir/Icon-72.png"
cp "$SYS_PREFIXROOT/build/$SYS_APPNAME/artwork-144.png" "$cmakedir/Icon-72@2x.png"
cp "$SYS_PREFIXROOT/build/$SYS_APPNAME/artwork-60.png" "$cmakedir/Icon-60.png"
cp "$SYS_PREFIXROOT/build/$SYS_APPNAME/artwork-120.png" "$cmakedir/Icon-60@2x.png"
cp "$SYS_PREFIXROOT/build/$SYS_APPNAME/artwork-76.png" "$cmakedir/Icon-76.png"
cp "$SYS_PREFIXROOT/build/$SYS_APPNAME/artwork-152.png" "$cmakedir/Icon-76@2x.png"
# go full screen on retina displays!
cp "$SYS_PREFIXROOT/build/$SYS_APPNAME/retina.png" "$cmakedir/Default-568h@2x.png"

make_soundfile_ios()
{
  cp "$1" "$cmakedir"
}
make_sounds make_soundfile_ios

echo " => preparing plist.."
configsrc=loaders/ios/Info.plist.in
ac_output $configsrc $SYS_TMPDIR/tmp.xml
assertfile $SYS_TMPDIR/tmp.xml
cat $SYS_TMPDIR/tmp.xml | sed '/^#/d' > "$SYS_PREFIXROOT/build/$SYS_APPNAME/Info.plist"
cp "$IOSSDK/ResourceRules.plist" "$SYS_PREFIXROOT/build/$SYS_APPNAME/ResourceRules.plist"

echo " => preparing custom config.."
headersrc=loaders/ios/config_custom.h.in
ac_output loaders/ios/config_custom.h.in "$cmakedir/config_custom.h"
assertfile "$cmakedir/config_custom.h"

echo " => building loader.."
xcodedir=`mktemp -d $SYS_TMPDIR/tmp.XXXXXX`
cd $xcodedir
veval "cmake -GXcode $cmakedir"
asserterror $?
#  xcodebuild -configuration Release | grep -A 2 error
veval "xcodebuild -configuration Release"
asserterror $?
cd $here
tmpappdir=$xcodedir/Release-iphoneos/$SYS_APPNAME$SYS_APPFIX
if [ ! -d $tmpappdir ]; then
  tmpappdir=$xcodedir/Release/$SYS_APPNAME$SYS_APPFIX
fi
assertfile $tmpappdir

echo " => verifying application.."

osxver=`sw_vers -productVersion`
if [ `echo "10.9.5\n$osxver" | sed 's/^10\.//' | sort -g | head -1` == "9.5" ]; then
  checkfail=`codesign --verify --no-strict $tmpappdir 2>&1`
else
  checkfail=`codesign --verify $tmpappdir 2>&1`
fi
if [ "$checkfail" ]; then
  echo "ERROR: $SYS_APPNAME build was not successful [$checkfail]"
  exit 1
fi

echo " => relocating application.."
rmifexists "$tgtdir"
cp -R $tmpappdir $tgtdir

echo " => cleaning up.."
rm -rf "$cmakedir" "$xcodedir" 2> /dev/null

#eof
