#!/bin/sh
# LambdaNative - a cross-platform Scheme framework
# Copyright (c) 2009-2013, University of British Columbia
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or
# without modification, are permitted provided that the
# following conditions are met:
#
# * Redistributions of source code must retain the above
# copyright notice, this list of conditions and the following
# disclaimer.
#
# * Redistributions in binary form must reproduce the above
# copyright notice, this list of conditions and the following
# disclaimer in the documentation and/or other materials
# provided with the distribution.
#
# * Neither the name of the University of British Columbia nor
# the names of its contributors may be used to endorse or
# promote products derived from this software without specific
# prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
# CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
# NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

ios_subst()
{
  ac_subst IOS_OBJC_DEFINES "@$1/IOS_objc_defines"
  ac_subst IOS_XML_PERMISSIONS "@$1/IOS_xml_permissions"
  ac_subst IOS_XML_REQUIREDDEVICECAP "@$1/IOS_xml_requireddevicecap"
}
ios_subst loaders/ios
for m in $modules; do
  modpath=`locatedir modules/$m silent`
  ios_subst $modpath
done
ios_subst `locatedir apps/$SYS_APPNAME`

tgtdir="$SYS_PREFIX/$SYS_APPNAME$SYS_APPFIX"
srcdir=`pwd`"/loaders/ios"
cmakedir=`mktemp -d tmp.XXXXXX`
cmakedir=`pwd`"/$cmakedir"
cd $here
ac_output $srcdir/CMakeLists.txt $cmakedir/CMakeLists.txt
cp $srcdir/*.m $cmakedir
cp $srcdir/*.mm $cmakedir
cp $srcdir/*.h $cmakedir

echo " => preparing icons.."
cp "$SYS_PREFIXROOT/build/$SYS_APPNAME/artwork-57.png" "$cmakedir/Icon.png"
cp "$SYS_PREFIXROOT/build/$SYS_APPNAME/artwork-114.png" "$cmakedir/Icon@2x.png"
cp "$SYS_PREFIXROOT/build/$SYS_APPNAME/artwork-72.png" "$cmakedir/Icon-72.png"
cp "$SYS_PREFIXROOT/build/$SYS_APPNAME/artwork-144.png" "$cmakedir/Icon-72@2x.png"
cp "$SYS_PREFIXROOT/build/$SYS_APPNAME/artwork-60.png" "$cmakedir/Icon-60.png"
cp "$SYS_PREFIXROOT/build/$SYS_APPNAME/artwork-120.png" "$cmakedir/Icon-60@2x.png"
cp "$SYS_PREFIXROOT/build/$SYS_APPNAME/artwork-76.png" "$cmakedir/Icon-76.png"
cp "$SYS_PREFIXROOT/build/$SYS_APPNAME/artwork-152.png" "$cmakedir/Icon-76@2x.png"
# go full screen on retina displays!
cp "$SYS_PREFIXROOT/build/$SYS_APPNAME/retina.png" "$cmakedir/Default-568h@2x.png"

make_soundfile_ios()
{
  cp "$1" "$cmakedir"
}
make_sounds make_soundfile_ios

echo " => preparing plist.."
configsrc=loaders/ios/Info.plist.in
ac_output $configsrc tmp.xml
assertfile tmp.xml
cat tmp.xml | sed '/^#/d' > "$SYS_PREFIXROOT/build/$SYS_APPNAME/Info.plist"

echo " => preparing custom config.."
headersrc=loaders/ios/config_custom.h.in
ac_output loaders/ios/config_custom.h.in "$cmakedir/config_custom.h"
assertfile "$cmakedir/config_custom.h"

echo " => building loader.."
xcodedir=`mktemp -d tmp.XXXXXX`
xcodedir=`pwd`"/$xcodedir"
cd $here
cd $xcodedir
veval "cmake -GXcode $cmakedir"
asserterror $?
#  xcodebuild -configuration Release | grep -A 2 error
veval "xcodebuild -configuration Release"
asserterror $?
cd $here
tmpappdir=$xcodedir/Release-iphoneos/$SYS_APPNAME$SYS_APPFIX
if [ ! -d $tmpappdir ]; then
  tmpappdir=$xcodedir/Release/$SYS_APPNAME$SYS_APPFIX
fi
assertfile $tmpappdir

echo " => verifying application.."
checkfail=`codesign --verify $tmpappdir 2>&1`
if [ "$checkfail" ]; then
  echo "ERROR: $SYS_APPNAME build was not successful"
  exit 1
fi

echo " => relocating application.."
rmifexists "$tgtdir"
cp -R $tmpappdir $tgtdir

echo " => cleaning up.."
rm -rf "$cmakedir" "$xcodedir" 2> /dev/null

#eof