#!/bin/sh
# LambdaNative - a cross-platform Scheme framework
# Copyright (c) 2009-2014, University of British Columbia
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or
# without modification, are permitted provided that the
# following conditions are met:
#
# * Redistributions of source code must retain the above
# copyright notice, this list of conditions and the following
# disclaimer.
#
# * Redistributions in binary form must reproduce the above
# copyright notice, this list of conditions and the following
# disclaimer in the documentation and/or other materials
# provided with the distribution.
#
# * Neither the name of the University of British Columbia nor
# the names of its contributors may be used to endorse or
# promote products derived from this software without specific
# prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
# CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
# NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

echo " => making $SYS_PLATFORM zip archive.."
pkgfile=$SYS_PREFIXROOT/packages/$SYS_APPNAME-$SYS_APPVERSION-$SYS_PLATFORM.zip
if [ -f $pkgfile ]; then
  rm $pkgfile
fi
cd $SYS_PREFIX
veval "zip -q -y -r $pkgfile ${SYS_APPNAME}.app"
cd $here
assertfile $pkgfile
echo "=== $pkgfile"

echo " => preparing exportArchive plist.."
configsrc=loaders/ios/exportOptions.plist.in
ac_output $configsrc $SYS_TMPDIR/tmp.xml
assertfile $SYS_TMPDIR/tmp.xml
if [ $SYS_MODE = release ]; then
  sed -i '' "s/development/app-store/g" $SYS_TMPDIR/tmp.xml
fi
cat $SYS_TMPDIR/tmp.xml | sed '/^#/d' > "$SYS_PREFIXROOT/build/$SYS_APPNAME/exportOptions.plist"

ipapath=$SYS_PREFIXROOT/packages
ipafile=$ipapath/$SYS_APPNAME-$SYS_APPVERSION-$SYS_PLATFORM.ipa
eopfile=$SYS_PREFIXROOT/build/$SYS_APPNAME/exportOptions.plist
expath=$SYS_PREFIXROOT/build/$SYS_APPNAME/export

echo " => making $SYS_PLATFORM ipa.."
if [ -f $ipafile ]; then
  rm $ipafile
fi
rmifexists "$expath"
veval "xcodebuild -exportArchive -archivePath $SYS_PREFIX/$SYS_APPNAME-$SYS_APPVERSION.xcarchive -exportPath $expath -exportOptionsPlist $eopfile"
assertfile $expath/$SYS_APPNAME.ipa
cp $expath/$SYS_APPNAME.ipa $ipafile
echo "=== $ipafile"

#eof
