#!/bin/sh
# LambdaNative - a cross-platform Scheme framework
# Copyright (c) 2009-2013, University of British Columbia
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or
# without modification, are permitted provided that the
# following conditions are met:
#
# * Redistributions of source code must retain the above
# copyright notice, this list of conditions and the following
# disclaimer.
#
# * Redistributions in binary form must reproduce the above
# copyright notice, this list of conditions and the following
# disclaimer in the documentation and/or other materials
# provided with the distribution.
#
# * Neither the name of the University of British Columbia nor
# the names of its contributors may be used to endorse or
# promote products derived from this software without specific
# prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
# CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
# NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#  an ipa is not needed anymore? 
# echo " => making iphone ipa archive.."
# tmpdir=`mktemp -d tmp.XXXXXX`
# mkdir $tmpdir/Payload
# cp -R $SYS_PREFIX/$SYS_APPNAME.app $tmpdir/Payload
# cp $SYS_PREFIXROOT/build/$SYS_APPNAME/artwork-1024.png $tmpdir/iTunesArtwork 
# cd $tmpdir
# mkdir -p "$SYS_PREFIXROOT/packages"
# pkgfile=$SYS_PREFIXROOT/packages/$SYS_APPNAME-$SYS_APPVERSION-iphone.ipa
# if [ -f $pkgfile ]; then
#   rm $pkgfile
# fi
# /usr/bin/zip -9 -y -r $pkgfile Payload iTunesArtwork
# cd $here
# assertfile $pkgfile
# rm -rf $tmpdir
echo " => making $SYS_PLATFORM zip archive.."
pkgfile=$SYS_PREFIXROOT/packages/$SYS_APPNAME-$SYS_APPVERSION-$SYS_PLATFORM.zip
if [ -f $pkgfile ]; then
  rm $pkgfile
fi
cd $SYS_PREFIX
veval "zip -q -y -r $pkgfile ${SYS_APPNAME}.app"
cd $here
assertfile $pkgfile
echo "=== $pkgfile"

#eof