(namespace ("" 
   make-class
   make-generic
   make-method
   add-method
   make
   initialize
   slot-ref
   slot-set!
   class-of
   class-direct-supers
   class-direct-slots
   class-cpl
   class-slots
   generic-methods
   method-specializers
   method-procedure
   allocate-instance
   initialize
   compute-cpl
   compute-slots
   compute-getter-and-setter
   compute-apply-generic
   compute-methods
   compute-method-more-specific?
   compute-apply-methods
   <pair>
   <null>
   <boolean>
   <symbol>
   <procedure>
   <number>
   <vector>
   <char>
   <string>
   <input-port>
   <output-port>
   <class>
   <top>
   <object>
   <procedure-class>
   <entity-class>
   <generic>
   <method>
))

;; eof
