/*
 * This file is generated by fsss program.
 * If you want to modify this file modify "tbl.fsss" instead.
 */
#ifndef _FSSS_conv_tbl_H_
#define _FSSS_conv_tbl_H_
#include <sys/types.h>
#include "extern.h"

__BEGIN_DECLS
struct conv_tbl * iconv_conv_tbl_search(const char *key);
__END_DECLS

#endif /* !_FSSS_conv_tbl_H_ */
