#!/bin/sh
# LambdaNative - a cross-platform Scheme framework
# Copyright (c) 2009-2013, University of British Columbia
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or
# without modification, are permitted provided that the
# following conditions are met:
#
# * Redistributions of source code must retain the above
# copyright notice, this list of conditions and the following
# disclaimer.
#
# * Redistributions in binary form must reproduce the above
# copyright notice, this list of conditions and the following
# disclaimer in the documentation and/or other materials
# provided with the distribution.
#
# * Neither the name of the University of British Columbia nor
# the names of its contributors may be used to endorse or
# promote products derived from this software without specific
# prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
# CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
# NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

rmifexists "$apptgtdir"
mkdir "$apptgtdir"
tmpdir=`mktemp -d tmp.XXXXXX`
if [ `is_gui_app` = yes ]; then
  cp bootstraps/x11/x11_microgl.c $tmpdir 
fi
if [ `is_standalone_app` = "no" ]; then
  cp bootstraps/common/main.c $tmpdir
fi
cd $tmpdir

sounddir=`locatedir apps/$SYS_APPNAME/sounds silent`
if [ -d "$sounddir" ]; then
  echo "Sound is currently not supported on linux486!!!"
  return;
fi

echo " => compiling application.."
tgt=$apptgtdir/$SYS_APPNAME$SYS_EXEFIX
if [ `is_standalone_app` = "yes" ]; then
  veval "$SYS_CC -I$SYS_PREFIX/include \
    -DUSECONSOLE -o $tgt \
    -L/usr/local/linux/i486-linux/lib \
    -L$SYS_PREFIX/lib -lpayload -lrt -lutil -lpthread -ldl -lm"
else
  if [ `is_gui_app` = yes ]; then
    echo "GUI applications are currently not supported on linux486!!!"
    return;
  else
    veval "$SYS_CC -I$SYS_PREFIX/include \
      -DUSECONSOLE main.c -o $tgt \
      -L/usr/local/linux/i486-linux/lib \
      -L$SYS_PREFIX/lib -lpayload -lrt -lutil -lpthread -ldl -lm"
  fi
fi
asserterror $?
assertfile $tgt
if [ ! "X$SYS_MODE" = "Xdebug" ]; then
  $SYS_STRIP $tgt
  asserterror $?
fi
cd $here

echo " => cleaning up.."
rm -rf "$tmpdir"

#eof