#!/bin/sh
# LambdaNative - a cross-platform Scheme framework
# Copyright (c) 2009-2013, University of British Columbia
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or
# without modification, are permitted provided that the
# following conditions are met:
#
# * Redistributions of source code must retain the above
# copyright notice, this list of conditions and the following
# disclaimer.
#
# * Redistributions in binary form must reproduce the above
# copyright notice, this list of conditions and the following
# disclaimer in the documentation and/or other materials
# provided with the distribution.
#
# * Neither the name of the University of British Columbia nor
# the names of its contributors may be used to endorse or
# promote products derived from this software without specific
# prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
# CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
# NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

GAMBIT_DEFS="-D___LIBRARY -D___PRIMAL"
STAGING_DIR=`ls -1d $OPENWRTSDK/staging_dir`
SDKROOT=`ls -1d $STAGING_DIR/target*`
CROSS=`ls -1d $STAGING_DIR/toolchain*/bin/*gcc | head -n 1 | sed 's/gcc$//'`
SYS_OPENWRTTARGET=`basename $CROSS | sed 's/-$//'`
SYS_ENV="$SYS_ENV STAGING_DIR=$STAGING_DIR"
SYS_CC=$CROSS"gcc $SYS_DEBUGFLAG -isysroot $SDKROOT -DOPENWRT -DLINUX $cflag_additions"
SYS_AR=$CROSS"ar"
SYS_RANLIB=$CROSS"ranlib"
SYS_STRIP=$CROSS"strip"
SYS_NM=$CROSS"nm"
SYS_WINDRES=
SYS_EXEFIX=
SYS_APPFIX=

#eof
