#!/bin/sh
# LambdaNative - a cross-platform Scheme framework
# Copyright (c) 2009-2014, University of British Columbia
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or
# without modification, are permitted provided that the
# following conditions are met:
#
# * Redistributions of source code must retain the above
# copyright notice, this list of conditions and the following
# disclaimer.
#
# * Redistributions in binary form must reproduce the above
# copyright notice, this list of conditions and the following
# disclaimer in the documentation and/or other materials
# provided with the distribution.
#
# * Neither the name of the University of British Columbia nor
# the names of its contributors may be used to endorse or
# promote products derived from this software without specific
# prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
# CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
# NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

if [ $SYS_PLATFORM = $SYS_HOSTPLATFORM ]; then
  vecho " => checking for sane localhost OpenGL setup.."
  echo "#include <GL/gl.h>" > $SYS_TMPDIR/gltest.c
  echo "int main() { glOrtho(0,0,0,0,0,0); }" >> $SYS_TMPDIR/gltest.c
  gcc -Werror -o $SYS_TMPDIR/gltest $SYS_TMPDIR/gltest.c -I/usr/X11/include -I/usr/X11R6/include -L/usr/X11/lib -L/usr/X11R6/lib -lGL  > /dev/null 2> /dev/null
  asserterror $? "OpenGL headers are missing?"
fi
rmifexists $SYS_TMPDIR/gltest
rmifexists $SYS_TMPDIR/gltest.c

vecho " => checking for sane ALSA setup.."
echo "#include <alsa/asoundlib.h>" > $SYS_TMPDIR/alsatest.c
echo "int main() { snd_pcm_hw_params_t *hwparams; snd_pcm_hw_params_alloca(&hwparams); }" >> $SYS_TMPDIR/alsatest.c
gcc -Werror -o $SYS_TMPDIR/alsatest $SYS_TMPDIR/alsatest.c -lasound
asserterror $? "ALSA headers are missing?"
rmifexists $SYS_TMPDIR/alsatest
rmifexists $SYS_TMPDIR/alsatest.c

#eof
