#!/bin/sh
# LambdaNative - a cross-platform Scheme framework
# Copyright (c) 2009-2015, University of British Columbia
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or
# without modification, are permitted provided that the
# following conditions are met:
#
# * Redistributions of source code must retain the above
# copyright notice, this list of conditions and the following
# disclaimer.
#
# * Redistributions in binary form must reproduce the above
# copyright notice, this list of conditions and the following
# disclaimer in the documentation and/or other materials
# provided with the distribution.
#
# * Neither the name of the University of British Columbia nor
# the names of its contributors may be used to endorse or
# promote products derived from this software without specific
# prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
# CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
# NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

win_sysroot=`ls -1d ${WIN32SDK}/i?86-*mingw32* | head -n 1`
win_cross=`ls -1 ${WIN32SDK}/bin/*mingw32*-gcc | head -n 1 | sed 's/gcc$//'`

SYS_CC=$win_cross"gcc $SYS_DEBUGFLAG -isysroot $win_sysroot -DWIN32 -DWINVER=0x0501"
SYS_AR=$win_cross"ar"
SYS_RANLIB=$win_cross"ranlib"
SYS_STRIP=$win_cross"strip"
SYS_NM=$win_cross"nm"
SYS_STRIP=$win_cross"strip"
SYS_CPP=$win_cross"cpp"
SYS_AS=$win_cross"as"
SYS_LD=$win_cross"ld"
SYS_OBJCOPY=$win_cross"objcopy"
SYS_OBJDUMP=$win_cross"objdump"
SYS_READELF=$win_cross"readelf"
SYS_GPROF=$win_cross"gprof"
SYS_WINDRES=$win_cross"windres"
SYS_NM=$win_cross"nm"
SYS_EXEFIX=".exe"
SYS_APPFIX=

#eof
