name: fedora-build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: fedora
    runs-on: ubuntu-latest
    container:
      image: fedora:41

    steps:
    - uses: actions/checkout@v4
    - run: cat /etc/os-release
    - name: install dependencies
      run: |
        dnf -y install alsa-lib-devel ant autoconf automake bc curl gambit-c
        dnf -y install gcc gcc-c++ git inkscape ImageMagick-devel
        dnf -y install java-17-openjdk-devel libtool libXext-devel make
        dnf -y install mesa-libGL-devel mesa-libGLU-devel netpbm-devel patch
        dnf -y install perl-FindBin portaudio python3-sdkmanager sed tar tcl-devel
        dnf -y install texlive tree wget zip
    - name: prepare lambdanative
      run : |
       # Make directory to avoid errors during build
       mkdir -p /github/home/.cache/lambdanative
       cp SETUP.template SETUP
       cp PROFILE.template PROFILE
    - name: smoke tests
      run: |
       sh make.sh smoke
